---
# create groups and user
- name: create jetty group
  group:
    name=jetty
    system=yes
  tags:
    - flow
    - users
    - groups

- name: create flow group
  group:
    name=flow
    system=yes
  tags:
    - flow
    - users
    - groups

- name: create flow user
  user:
    name=flow
    comment="start flowing"
    group=flow
    groups=jetty
    home=/var/lib/flow
    system=yes
  tags:
    - flow
    - users
    - groups

# install flow software
- name: install supporting software
  apt: pkg={{ item }}
  with_items:
    - unzip
    - python-pip
  tags:
    - flow
    - install
    - packages

- name: install ansible supporting python packages
  pip: name={{ item }}
  with_items:
    - urlparse2
  tags:
    - flow
    - install
    - packages

- name: create root software directory
  file:
    dest=/opt/flow/lib/main
    state=directory
    owner=flow
    group=flow
  tags:
    - flow
    - install

- name: Flow | check to see if flow installed
  stat:
    path: /opt/flow/lib/main/Flow-0.3-BETA
  register: flow_install

- name: Flow | check to see if download exists
  stat:
    path: /tmp/Flow-0.3-BETA.zip
  register: flow_download
  when: flow_install.stat.exists == false

- name: download flow software
  get_url:
    url=http://software.newedgeengineering.net/thirdparty/net/startflowing/Flow-0.3-BETA.zip
    dest=/tmp/
  when: flow_install.stat.exists == false and flow_download.stat.exists == false
  register: flow_downloaded
  tags:
    - flow
    - install

- name: Flow | extract flow to /opt/flow/lib/main
  command: "unzip -u /tmp/Flow-0.3-BETA.zip -d /opt/flow/lib/main"
  when: flow_downloaded|changed
  register: flow_extracted
  tags:
    - flow
    - install

- name: move extracted Flow to include version number
  command: "mv /opt/flow/lib/main/Flow /opt/flow/lib/main/Flow-0.3-BETA"
  when: flow_extracted|changed
  tags:
    - flow
    - install

- name: correct flow ownership and permissions
  file:
    path="/opt/flow/lib/main/Flow-0.3-BETA"
    owner=flow
    recurse=yes
    state=directory
    mode=0755
  when: flow_extracted|changed
  tags:
    - flow
    - install

- name: correct extracted files permissions
  shell: "chmod 0644 -R /opt/flow/lib/main/Flow-0.3-BETA/*.{{ item }}"
  when: flow_extracted|changed
  with_items:
    - war
    - jar
    - xml
  tags:
    - flow
    - install

- name: update link to latest flow
  file:
    src="/opt/flow/lib/main/Flow-0.3-BETA"
    dest=/opt/flow/bin
    state=link
    owner=flow
    group=flow
  when: flow_extracted|changed
  tags:
    - flow
    - install

- name: create supporting directories
  file:
    dest={{ item }}
    state=directory
    mode=755
    owner=flow
    group=flow
  with_items:
    - /var/log/flow
    - /var/lib/flow
    - /var/lib/flow/flow
    - /var/lib/flow/.flow/
    - /var/lib/flow/.flow/database
    - /var/lib/flow/.flow/config
  tags:
    - flow
    - install

- name: create flow configuration
  template:
    dest=/var/lib/flow/.flow/config/flowconfig.groovy
    src=flowconfig.groovy.j2
    mode=644
    owner=flow
    group=flow
  notify:
    - restart flow
  tags:
    - flow
    - configuration

- name: create upstart configuration for flow
  template:
    dest=/etc/init/flow.conf
    src=flow.conf.j2
    mode=0644
    owner=root
    group=root
  notify:
    - restart flow
  tags:
    - flow
    - configuration

- name: Flow | Ensure postgresql database driver is in place
  include: postgresql.yml
  when: flow_database_type == 'postgresql'


# install plugins

